name: 更新页面访问统计

on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 每15分钟运行一次
    - cron: '0,15,30,45 * * * *'

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 完成
      run: echo "统计页面HTML是独立的，无需生成"
