name: 更新页面访问统计

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发（每15分钟更新一次）
  schedule:
    - cron: '0,15,30,45 * * * *'  # 每小时的0,15,30,45分钟
  # 当有新的访问记录时触发
  push:
    paths:
      - 'stats-data/access-logs.json'

# 添加权限配置
permissions:
  contents: write
  actions: read

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: 设置Node.js环境
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 显示当前时间
      run: |
        echo "当前UTC时间: $(date -u)"
        echo "当前本地时间: $(date)"
        echo "GitHub Actions运行时间: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
    - name: 安装依赖
      run: npm install
      
    - name: 生成统计页面
      run: node scripts/generate-stats.js
      
    - name: 检查文件变化
      run: |
        if [ -f "stats-page.html" ]; then
          echo "统计页面生成成功"
          ls -la stats-page.html
          echo "文件内容预览:"
          head -5 stats-page.html
        else
          echo "错误：统计页面未生成"
          exit 1
        fi
      
    - name: 提交统计页面更新
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add stats-page.html
        git status
        git commit -m "自动更新统计页面 [skip ci] - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "没有变化需要提交"
        git push
